version: "3.8"

services:
  redis:
    image: redis:7.0.11-alpine

  django:
    container_name: django
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True
    depends_on:
      - redis

  celery:
    container_name: celery1
    build: .
    command: celery --app=core worker -l INFO -Q celery,celery:1,celery:2,celery:3
    volumes:
      - .:/code
    depends_on:
      - redis
      - django

  # celery2:
  #   container_name: celery2
  #   build:
  #     context: ./standalone-cworker
  #     dockerfile: Dockerfile
  #   command: celery -A celerytask worker --loglevel=INFO -Q queue2
  #   volumes:
  #     - ./standalone-cworker:/code
  #   depends_on:
  #     - redis
  #     - django
